### ISSUE TITLE
More movement stutter the higher the fps

### ISSUE THREAD

**Issue by 0BS1N** [artemalive/Quake-III-Arena#16]
I usually play at com_maxfps 250, but with this .exe i notice some kind of movement stutter; when i look at other players they move just fine but when I AD strafe I can see a noticeable stuttering in my movement. So I thought it should just play at com_maxfps 500 or higher but that made my movement even more stuttery.

I have and AMD RX 480 GPU and a i7 4790k

I tried recording but the issue wasn't very noticeable at 60fps (the framerate of the recording), but to get to the point, when r_rederAPI is set to 1 or 2, the higher the com_maxfps cvar is set to, the more stuttery movement feels.

**Comment by kennyalive** [comment]
I can check that later, thanks noticing this. Partially it could be driver issue.  In general if you play original Q3 game you can expect this (even with r_renderAPI set to OpenGL), the higher frame rate the worse behavior of physics, might be due to time resolution of 1ms, so if you play at 500 fps the game can't measure time properly. I believe in the past a lot of players locked game to 125 fps because on one hand it provided high enough fps on the other hand it's only 1/8 of time resolution so physics is still more or less good. Of course it's different in modern fps games where you often want to lock to 240 fps if you have good monitor.

**Comment by kennyalive** [comment]
> when r_rederAPI is set to 1 or 2, the higher the com_maxfps cvar is set to, the more stuttery movement feels.

Just checked original Quake 3 executable and as I expected it behaves similarly (this project does not try to change original engine behavior). Played with 500 FPS limit and it's pretty stuttery.
