### ISSUE TITLE
Bring flares back

### ISSUE THREAD

**Issue by ensiform** [artemalive/Quake-III-Arena#5]
Their rendering was fixed in the [ioquake3](https://github.com/ioquake/ioq3/blob/master/code/renderergl1/tr_flares.c) project some time ago, and they do exist in many standard Q3 maps.

**Comment by kennyalive** [comment]
Hi, @ensiform. This project does not provide enhancement to Q3 graphics fratures. The goal is to preserve original Q3 look and feel. Flares were removed since they are broken in Q3. Also this project is not a competitor to ioquake3, it’s just a maintainance of the original q3 codebase with intention to keep it small and easy to build.
