### ISSUE TITLE
crash with r_smp=1

### ISSUE THREAD

**Issue by suijingfeng** [artemalive/Quake-III-Arena#8]
does your edition support multi-thread?

**Comment by kennyalive** [comment]
No, it doesn't. Right now no plans to fix r_smp since it never worked for me on windows. In general I try to fix functionality that worked in original Q3 in order to preserve Q3 as closely as possible to its original shape.

**Comment by suijingfeng** [comment]
@kennyalive
But it seems that original Q3 do support r_smp = 1, see http://fabiensanglard.net/quake3/renderer.php and q3a source. I am learning knowledge about multi-thread right now, but only find that almost all successor repository (ioq3, ec- version) remove this feature. i am noob in 3D engine, so I intend to ask you for advice.  What's the reason r_smp never worked on windows?  Is there any possible to reimplement this on linux? any document? thanks.

**Comment by kennyalive** [comment]
Hi @suijingfeng,
honestly I don't know why it does not work on windows. Probably it worked at some period of time (maybe before Win2K). I think this feature is not so important nowadays - no need to speed up Q3 it's a  fast game on modern hardware and threading support it's always a large chunk of complexity in the code. Still I didn't remove it yet, maybe I'll take a look at it at some point and if the fix is simple I'll fix it, otherwise no plans to do a major rewrites of this feature.
Talking about multithreading, probably this project is not the best place to learn about it. Maybe you can search something on the internet about task-based threading systems used in modern engines or if you are using c++ that c++ std::thread could be useful as starting point.
